###########################
## Better Nick by DomeDD ##
###########################

Config:
    Auto Update Check: true
    Auto Update Download: true
    API Mode: false
    Use Vault: false
    # If true, you won't get a nickname on join (if the client enabled AutoJoin and has the Permissions)
    Lobby Mode: false
    # Nick Name Prefix for chat messages; I recommend to leave Display Name Prefix empty
    Display Name Prefix: ''
    # Nick Name Prefix for nametag; I recommend to leave Name Tag Prefix empty if you didn't install NametagEdit
    Name Tag Prefix: ''
    # Nick Name Prefix for tablist
    Tablist Name Prefix: '&8Player &e| &7'
    # Overwrites the Player Prefix, on unnick the Player will get his old Prefix (if "Config.Use Vault" == true)
    Permissions System Player Prefix: '&8Player &e| &7'
    # Be aware of that the Client gets killed and respawned when Skin Self Update is true
    Skin Self Update: false
    Nicked Actionbar: true
    Keep NickName On Quit: false
MySQL:
    Enabled: false
    Username: root
    Password: password
    Database: nicknames
    Host: localhost
    Port: '3306'
Messages:
    Enabled: true
    Nick Name Set: '&8[&5BetterNick&8] &7Your nickname is &5[NAME]&7.'
    Nick Name Removed: '&8[&5BetterNick&8] &7Your nickname has been removed.'
    Nick Set Error: '&8[&5BetterNick&8] &7Your name could not be changed.'
    Skin Set: '&8[&5BetterNick&8] &7You have a new skin now.'
    Skin Removed: '&8[&5BetterNick&8] &7Your skin has been removed.'
    Skin Set Error: '&8[&5BetterNick&8] &7Your skin could not be changed.'
    See Real Name: '&8[&5BetterNick&8] &7The real name of &3[PLAYER] &7is &e[NAME]&7.'
    See Real Name Error: '&8[&5BetterNick&8] &7This Player is not online!'
    See Nick: '&8[&5BetterNick&8] &7Your nickname is &e[NAME]&7.'
    Get Nicked Players Header: '&8[&5BetterNick&8] &7Listing all nicked players and their real names...'
    Get Nicked Players: '&8[&5BetterNick&8] &6[ID]&7: The real name of &3[PLAYER] &7is &e[NAME]&7.'
    Get Nicked Players Error: '&8[&5BetterNick&8] &7At the moment no player is nicked.'
    Nicked Actionbar: '&8[&5BetterNick&8] &eYou are nicked as &3[NAME]&e.'
    AutoNick Turned On: '&8[&5BetterNick&8] &7You turned on autonick.'
    AutoNick Turned Off: '&8[&5BetterNick&8] &7You turned off autonick.'
    Reloaded: '&8[&5BetterNick&8] &7You successfully reloaded the config files.'
    No Permissions: '&8[&5BetterNick&8] &7You don''t have the permissions to do that.'
Addons:
    AutoNick Item:
        Enabled: false
        Get On Server Join: true
        Get On World Change:
        - world
        Enabled Worlds:
        - world
        # ID:SubID, Displayname, Slot
        Item: 421:0, &5Nick Tool, 4
        Item Moveable: false
        Inventory:
            Name: '&8[&5BetterNick&8] &5AutoNick'
            # ID:SubID, Displayname, Slot (has to be the same slot as at "Addons.AutoNick Item.Inventory.AutoNick False")
            AutoNick True: 348:0, &7AutoNick &8>> &2TRUE, 4
            # ID:SubID, Displayname, Slot (has to be the same slot as at "Addons.AutoNick Item.Inventory.AutoNick True")
            AutoNick False: 289:0, &7AutoNick &8>> &cFALSE, 4
    Random Nick Gui:
        Enabled: false
        Inventory:
            Name: '&5Random Nicks'
            # Only change the colorcode. Don't add anything else
            Nick Item Name: '&5[NAME]'
            Nick Item Lore: '&7Click to set a new nickname.'
NickNames List:
- 'abcplayer'
- 'xxHolyMolyxx'
- '123Playz123'
- 'MasterOfGamez'
- 'YoshiGamesHD'
- 'Randiii'
- '556NoSkillz'
- 'IHaveNoAimxx'
- 'LoLzxD'
- 'NiceGG'
- 'Gold_Swordy'
- 'xXD_DXx'
- 'C4A14'
- 'Desert_Hill_HD'
- 'M0_Z!ll4'
- 'TiAnTi'
- 'Cob_Website'
- 'Allih'
- 'alex_ander'
- '2eZ4us'
- 'Floridana'
- '_xXHDLPXx_'
- 'Johnnnyy'
- 'Plate_123'
- 'xxXGirlsss'
- 'kryBabe'
- 'Storm_Hunter'
- 'l0L_G4M3r'
- 'WorldWiideee'
- 'Wooliyyy'
- 'xx8msxx'
- '_St3xxis_'
- 'tryHarderrr'
- 'ClownnXxX'
- 'dope88'
- 'ninja_cow'
- 'LoyLoyLoy'
- 'xxImBackxx'
- 'ImNotBlack'
- 'bagbakc98'
- 'snow_onGround'
- 'sammy001'
- 'Crazyy4'
- 'Gay4Life'
- 'NoFaceMan'
- 'AlpMen'
- 'GruhGruh_'
- '_-xXx-_'
- 'Name_is_Cenaa'
- 'samm_hd'
- 'Butternesss'
- 'Ohhl3333'
- 'No360'
- 'xXCanyonXx'
- 'itz_M3_PvP'
- 'Denniese_LP'
- 'No_One_Can'
- 'Cookingar'
- 'Gamingin'
- '88studgell'
- 'xXFoot_Ball'
- 'BloomGames'
- 'Hope_36'
- 'Sleep_Park_HD'
- 'Tennis_Fan2'
- '123HDLPXD'
- 'Tired_A_F'
- 'Arselnal'
- 'Cheap_Pixii'
- 'Loving_Me1'
- 'hantoren_HD'
- 'engontiy'
- 'obreeel'
- 'antenda69'
- 'funotyond89'
- 'great_gorat'
- 'wolirerer'
- 'ABCDEF'
- '69_Me_69'
- 'ohofornot'
- 'oppuestarent'
- 'Latinum_eZ'
- 'erlosieee'
- 'Hentai_69'
- 'xxiTzKembo_PvP'
- 'xSt3giex'
- 'ccNayomcc'
- 'yX_NoCare_Xy'
- 'issolla'
- 'yotare'
- 'vodka_gutr'
- 'AraseelYT'
- 'NickoooPvP_YT'
Skins List:
- 'C418'
- 'Earstorm'
- 'Hola'
- 'vexx21322'
- 'FoidzaFlow'
- 'Inzuki'
- 'Noggin'
- 'Anomaly'
- 'Whomobile'
- 'Glent'
- 'Nikmi'
- 'Gogo'
- 'Asrue2'
- 'swampie'
- 'torteela'
- 'muhammad'
- 'Dwragon'
- 'iam2little'
- 'Minecrafter'
- 'Conan3D'
- 'andersonmat'
- 'Swedman'
- 'CapnAwesom'
- 'elbowgrease12'
- 'Skype'
- 'Woodenwindows'
- 'SeanNanoware'
- 'Frog'
- '00Fraday00'
- 'Yumcake'
- 'Settler'
- 'ddrl46'
- '8zero'
- 'southworth'
- 'Micsi'
- 'A_Glitch'
- 'speedblader03'
- 'MightyMega'
- 'Seanm07'
- 'Chamonze'
- 'MokkaCicc'
- 'Notsuru'
- 'sade1212'
- 'inacio'
- 'Snipex01'
- 'Foogles'
- 'Mzilla'
- 'Hackscore'
- 'Cool'
- 'Pedobuddy'
- 'Yunie'
- 'CherryJimbo'
- 'Fury'
- 'God'
- 'Romaji'
- 'chrisjon'
- 'Gravn'
- 'Spikespiegel'
- 'gagamel'
- 'ManningQB18'
- 'AndrewPH'
- 'Nether'
- 'Frewp'
- 'Explorer'
- 'SunriseMoon'
- 'Cheapshot'
- 'hug9000'
- 'Computrix'
- 'KingSam'
- 'Fish_warden'
- 'liv3d'
- 'Neath'
- 'Rixxz2'
- 'xHellfire'
- 'SolWolf'
- 'Razorlance'
- 'Dread'
- 'Israphel'
- 'Ryzo'
- 'Jakeobs'
- 'stolengoose'
- 'elrobto'
- 'TheJohan'
- 'subtraho'
- 'Creeper_Boss'
- 'Eisblut'
- 'mendo89'
- 'Graytico'
- 'Peter'
- 'jacksturrr416'
- 'phone'
- 'ControlFreak92'
- 'GRUML3N'
NickNames Black List:
- 'DomeDD'